normalisation du fichier d'entrée
MieuxVoter/majority-judgment-tracker pull request #9
Opened 2022-02-21 17:23 UTC by sballe73

2022-02-22 00:16 UTC, Ipuch commented
Ton commit fait bien avancer la reflexion :+1: . On peut s'appeler au besoin. Peut-etre que je vais me permettre de faire des choses ce week-end.

2022-02-22 00:17 UTC, Ipuch requested changes
Ton commit fait bien avancer la reflexion :+1 . On peut s'appeler au besoin. Peut-etre que je vais me permettre de faire des choses ce week-end.

2022-02-22 00:17 UTC, Ipuch commented on standardisation.csv
> +positsitive,plutot positive,plutot negative,negative,sans opinion,nan,nan,Passable B,2.0*intention_mention_1/3,1.0*intention_mention_1/3+1.0*intention_mention_2/3,2.0*intention_mention_2/3,0,2.0*inte
Après reflexion, plusieurs éléments:

- Il y a une fautre dans nos .csv, à corriger "positsitive"
- Je ne comprends pas l'intéret de normaliser les mentions à 100 % en amont.  Voici ce que je propose:
- Il faut un csv qui standardise pour un nombre défini de mentions.
Ex : si on choisit d'avoir 4 mentions quelque soit les sondages, il nous faut un .csv de la forme,
mention, mention attribuée,
positive, "excellent, très bien, bien"
plutot positive, "assez bien, passable"
plutot negative, "passable, insuffisant"
negative, "a rejeter"
sans opinion, "ne connait pas assez la personne", "ne se prononce pas"

ça nous permettra d'ajouter toutes les mentions quelque soit le "langage" de l'enquete.

Aussi très important, il ne faut pas cacher des calculs dans les .csv.

Ainsi, il n'y a qu'un seul calcul qui arrive si on en enleve les sans opinion, Il faut recalculer la proportion pour chacune des mentions en retirant le % de sans opinions. Ce calcul doit etre effectué dans une fonction séparée, "remove_undecided". Tous les if cases en fonction du nombre initial de mention dans l'enquete doivent être gérés dans cette sous-fonction.

Ensuite le reste des calculs peut-etre fait sur les votes même si la somme est differente 100%

Une fonction de normalisation à 100% doit être créée et appelée dans la fonction plot_merit_profile, pour s'assurer que les totaux sont égaux à 100%.

2022-02-22 00:17 UTC, Ipuch commented on main.py
> +        df_sorted = sort_candidates_mj(survey, df_survey, nb_grades)
Retirer cet argument.

2022-02-22 00:17 UTC, Ipuch commented on main.py
> +    df=normalize_file(args.csv)
Il faudrait qu'on puisse appeler le csv avec different argument, la fonction s'appelerait à mon sens:
load_surveys(undecided = True/False, grade_number=4,5,6) et retourne un message d'erreur dans le cas ou le nombre de mention n'est pas adapté à la database.

2022-02-22 08:34 UTC, sballe73 commented on libs/majority_judgment_2.py
> +def majority_judgment(ref_id: str, data: Dict[str, List[float]] = None, reverse: bool = False):
le truc c'est qu'on est pas en nombre de votes actuellement, on est en pourcentage. Et selon les règles de normalisation j'ai besoin de deux chiffres après la virgule pour éliminer à la fin les erreurs d'arrondi. D'où le changement int->float

2022-02-22 08:35 UTC, sballe73 commented on libs/majority_judgment_2.py
> +        raise ValueError("note the same number of vote for each candidate in " + ref_id + " - " + str(data))
le check des votes se fait ici, avoir l'info dans le message d'erreur evite de passer en mode debug pour iterer jusqu'à ce qu'on voit l'erreur, vraiment pratique.

2022-02-22 08:35 UTC, sballe73 commented on libs/normalize.py
> +#note, on perd des éléments en passant en aggrégat
je bascule dans la langue de minet qui meurt.

2022-02-22 08:36 UTC, sballe73 commented on libs/normalize.py
> +    return df
ok

2022-02-22 08:44 UTC, sballe73 commented on standardisation.csv
> +positsitive,plutot positive,plutot negative,negative,sans opinion,nan,nan,Passable B,2.0*intention_mention_1/3,1.0*intention_mention_1/3+1.0*intention_mention_2/3,2.0*intention_mention_2/3,0,2.0*inte
l'intérêt de normaliser en amont c'est de gagner la capacité d'agréger des sondages et aussi de les comparer.
Le calcul dans le csv c'est une façon de faire du paramétrage pour une grande quantité de types de sondages inconnus.
pour l'instant ça marche, on pourra changer plus tard si ça te dérange pas pour pouvoir se focaliser sur d'autres points avant.
Retirer les sans opinion, sauf erreur ne permet plus les calculs JM, à vérifier.
Dans l'ensemble je trouve que les votes par mention sous forme de % est une erreur, on perd de la précision et on doit gérer des erreurs d'arrondi. Avoir une source de données en nombre de votes "flat" serait plus propre.

2022-02-22 08:45 UTC, sballe73 commented on main.py
> +        df_sorted = sort_candidates_mj(survey, df_survey, nb_grades)
facilite franchement la recherche d'erreur dans la source de données

2022-02-22 08:46 UTC, sballe73 commented on main.py
> +    df=normalize_file(args.csv)
il y a des arguments optionnels déjà pour faire ce genre de choses.
La méthode adoptée de normalisation n'a jamais de database incompatiblen elle peut avoir une base contenant des lignes non présentes dans le fichier de standardisation que je ne gère pas encore.

2022-02-22 11:46 UTC, Ipuch commented on libs/majority_judgment_2.py
> +def majority_judgment(ref_id: str, data: Dict[str, List[float]] = None, reverse: bool = False):
Je comprends ton point.
Seulement ça n'est pas raisonnable de modifier une librairie externe. C'est comme ci on modifiait une libraire comme numpy parce que ça fait pas ce qu'on veut en entrée.

En somme, le problème vient de nous pas du jm.

Sur le fait qu'on ait un chiffre à virgule. Je pense que tant qu'on a un pas les données brutes on peut tenter un Hack en amont, exemple à chaud: multiplier par 1000, arrondir les votes et arrondir.
Peut-être à vérifier avec rida.

2022-02-22 11:46 UTC, Ipuch commented on libs/majority_judgment_2.py
> +        raise ValueError("note the same number of vote for each candidate in " + ref_id + " - " + str(data))
Même commentaire qu'au dessus je comprends l'intérêt personnel du point de vue début. Mais c'est une mauvaise idée de modifier la libraire.

2022-02-22 11:48 UTC, Ipuch commented on main.py
> +        df_sorted = sort_candidates_mj(survey, df_survey, nb_grades)
Tu peux faire un print dans la console au besoin, mais ce n'est pas nécessaire, pour la fonction.

2022-02-28 03:57 UTC, Ipuch commented
I've cleaned the code. We now have a system to aggregate #7 and to handle surveys without no opinion grades #5. Need to check if we have enough surveys to plot the evolution over time of the ranking.

2022-02-28 03:58 UTC, merged